# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sisk-engine: [ 'Default', 'Cadente' ]
    
    defaults:
      run:
        shell: bash
        working-directory: ./tests/Sisk.Core
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.sisk-engine }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Test with ${{ matrix.sisk-engine }} engine
      env:
        SISK_TEST_ENGINE: ${{ matrix.sisk-engine }}
      run: dotnet test --verbosity normal